/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/core/utility.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/video/tracking.hpp>


using namespace cv;
using namespace std;

/* Header for class com_example_albertreed_asuforiacppsupport_OpencvNativeClass */

#ifndef _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#define _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif

int toGray(Mat img, Mat &Gray);

JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

  JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_nativePoseEstimation
    (JNIEnv *, jclass, jlong);

JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_getReferencePoints
    (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
