/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <stdio.h>
#include <opencv2/opencv.hpp>
#include <opencv2/core.hpp>
#include <opencv2/core/utility.hpp>
#include <opencv2/highgui/highgui.hpp>
#include <opencv2/features2d/features2d.hpp>
#include <opencv2/highgui.hpp>
#include <opencv2/imgproc.hpp>
#include <opencv2/calib3d.hpp>
#include <opencv2/video/tracking.hpp>
#include <android/log.h>
#include <string>


#define LOG_TAG "MYPRINT"
#define  LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG, LOG_TAG, __VA_ARGS__)


using namespace cv;
using namespace std;

/* Header for class com_example_albertreed_asuforiacppsupport_OpencvNativeClass */

#ifndef _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#define _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif

int toGray(Mat img, Mat &Gray);

void p(std::string s);

/*Not used but pretty self explanatory*/
JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*Implements the pose estimation problem in C++*/
  JNIEXPORT jobjectArray JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_nativePoseEstimation
    (JNIEnv *, jclass, jlong, jlong, jlong, jlong, jobjectArray, jobjectArray);

/*Finds reference points and descriptors*/
JNIEXPORT jobjectArray JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_getReferencePoints
    (JNIEnv * env, jclass, jlong addrFrame, jlong descriptorsAddr);


#ifdef __cplusplus
}
#endif
#endif
