/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_albertreed_asuforiacppsupport_PoseListener */

#ifndef _Included_com_example_albertreed_asuforiacppsupport_PoseListener
#define _Included_com_example_albertreed_asuforiacppsupport_PoseListener
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
