/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_albertreed_asuforiacppsupport_OpencvNativeClass */

#ifndef _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#define _Included_com_example_albertreed_asuforiacppsupport_OpencvNativeClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_albertreed_asuforiacppsupport_OpencvNativeClass
 * Method:    convertGray
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_convertGray
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     com_example_albertreed_asuforiacppsupport_OpencvNativeClass
 * Method:    nativePoseEstimation
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_example_albertreed_asuforiacppsupport_OpencvNativeClass_nativePoseEstimation
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
